name: logicblock
description: ""
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.7
  shared_preferences: ^2.5.4
  splashscreen: ^2.0.0
  webview_flutter: ^4.13.1
  


dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_upscaled.png" 


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/blockly/
    - assets/blockly/js/
    - assets/blockly/media/
  fonts:
    - family: JetBrainsMono
      fonts: 
        - asset: 'assets/fonts/JetBrainsMono-VariableFont_wght.ttf'
        - asset: 'assets/fonts/JetBrainsMono-Italic-VariableFont_wght.ttf'
          style: italic

    - family: Inter
      fonts:
        - asset: 'assets/fonts/Inter-VariableFont_opsz,wght.ttf'
        - asset: 'assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf'
          style: italic



